---
new_page_extension: md
auto_deploy: true
admin_path: static/admin
webhook_url: 
sections:
- type: directory
  path: site/content/post
  label: Post
  create: all
  match: "**/*"
- type: directory
  path: site/content
  label: Pages
  create: all
  match: "*"
- type: directory
  path: site/content/values
  label: Values
  create: all
  match: "**/*"
- type: directory
  path: site/content/contact
  label: Contact
  create: all
  match: "**/*"
- type: directory
  path: site/content/products
  label: Products
  create: all
  match: "**/*"
upload_dir: site/static/img
public_path: "/img"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_command: hugo -D
  publish_command: hugo
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.53
  publish_env:
  - hugo_version=0.46
  preview_output_directory: public
  output_directory: site/public
  instant_preview_command: hugo server -D -E -F --port 8080 --bind 0.0.0.0 --renderToDisk
    -d public
version: '0.53'
